name: Iris docker test
on:
  push
permissions:
  contents: write
  pull-requests: write
jobs:
  test_docker_image_creation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: iterative/setup-cml@v2
      - name: run unit tests
        run: |
          pip install -r requirements.txt
          python train/train.py
          pytest test/test.py -v 2>&1 > test_output.txt
          date +%s > date_file
          cat date_file >> test_output.txt
          docker build -t image`cat date_file` .
          docker images > docker_images
          docker rmi image`cat date_file` >> docker_deleted
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          touch report.md
          echo "Result" >> report.md
          echo "\`\`\`" >> report.md
          cat test_output.txt >> report.md
          echo "\`\`\`" >> report.md
          echo "metrics from training" >> report.md
          cat metrics.csv >> report.md
          echo "\`\`\`" >> report.md
          echo "Expected docker image name" >> report.md
          echo image`cat date_file` >> report.md
          echo "\`\`\`" >> report.md
          echo "Current images" >> report.md
          cat docker_images >> report.md
          echo "\`\`\`" >> report.md
          echo "Docker remove confirmation" >> report.md
          cat docker_deleted >> report.md
          cml comment create --publish report.md
